# Thank you for using my skript!!

# Enjoy

options:
    prefix: <##f2e038>&lEMOJIS
    emoji-chat-permission: emoji.sk
    chat-color: &f # White

## Do not change anything below if you are not experienced with skript!

on chat:
    if player has permission "{@emoji-chat-permission}":
        if message contains ":heart:":
            replace all ":heart:" in chat message with "<#ff000d>❤{@chat-color}"
        if message contains ":comet:":
            replace all ":comet:" in chat message with "<#17e8ff>☄{@chat-color}"
        if message contains ":yes:":
            replace all ":yes:" in chat message with "&a✔{@chat-color}"
        if message contains ":)" or ":(":
            replace all ":)" in chat message with "☺{@chat-color}"
            replace all ":(" in chat message with "☹{@chat-color}"
        if message contains ":skull:":
            replace all ":skull:" in chat message with "☠{@chat-color}"
        if message contains ":lightning:":
            replace all ":lightning:" in message with "<#ffe417>&l⚡{@chat-color}"
        if message contains ":star:":
            replace all ":star:" with "<#f7ff17>⭐{@chat-color}" in message
        if message contains ":fire:":
            replace all ":fire:" with "<#FF4500>🔥{@chat-color}" in message
        if message contains ":no:":
            replace all ":no:" with "&c❌{@chat-color}" in message
        if message contains "<3":
            replace all "<3" in chat message with "<#ff000d>❤{@chat-color}"
        

command /emojilist:
    trigger:
        send "{@prefix} List:"
        send ""
        send "{@prefix} &7• &f<3 &7→ <#ff000d>❤"
        send "{@prefix} &7• &f:heart: &7→ <#ff000d>❤"
        send "{@prefix} &7• &f:yes: &7→ &a✔"
        send "{@prefix} &7• &f:no: &7→ &c❌"
        send "{@prefix} &7• &f:) &7→ &f☺"
        send "{@prefix} &7• &f:( &7→ &f☹"
        send "{@prefix} &7• &f:skull: &7→ &f☠"
        send "{@prefix} &7• &f:star: &7→ <#f7f17>⭐"
        send "{@prefix} &7• &f:lightning: &7→ <#ffe417>&l⚡"
        send "{@prefix} &7• &f:fire: &7→ <#FF4500>🔥"
        send "{@prefix} &7• &f:comet: &7 <#17e8ff>☄"

# - Xoyqe
# Out!

